name: CI(Unit/E2E Test)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  unit-test:
    name: Run unit tests using Vitest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Output yarn version
        run: |
          yarn --version
